#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

ynh_backup --src_path="$install_dir"

ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup --src_path="/etc/logrotate.d/$app"

ynh_backup --src_path="/etc/systemd/system/$app.service"

#=================================================
# BACKUP THE DATABASE
#=================================================
ynh_print_info --message="Backing up the postgresql database..."

ynh_psql_dump_db --database=$db_name > ./appdb.sql
ynh_psql_dump_db --database=$userdata_db_name > ./userdb.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
