#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's configuration file..."

secret_key=$(ynh_string_random --length=42)
ynh_app_setting_set --key=secret_key --value=$secret_key

ynh_config_add --template="superset_config.py" --destination="$install_dir/superset_config.py"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

# Prepare environment
python3 -m venv $install_dir/venv
localpath=$install_dir/venv/bin:$PATH
environment="FLASK_APP=superset SUPERSET_CONFIG_PATH=$install_dir/superset_config.py SUPERSET_SECRET_KEY=$secret_key"
export $environment

# Install and initialize Superset
pushd $install_dir
    source venv/bin/activate
    ynh_hide_warnings env $environment pip3 install "marshmallow<4" psycopg2 openpyxl python-ldap Pillow sqlalchemy-bigquery apache-superset==$(ynh_app_upstream_version)
    ynh_hide_warnings env $environment superset db upgrade
    ynh_hide_warnings env $environment superset init
    deactivate
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"  --wait_until="Running on http" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
