#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE USER DATABASE
#=================================================
ynh_script_progression "Removing user database for $app..."

# FIXMEhelpers2.1 ynh_psql_drop_db && ynh_psql_drop_user --db_user=$userdata_db_user --db_name=$userdata_db_name

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_logrotate

# Remove other various files specific to the app... such as :

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
